// 运行时状态 —— 所有运行时数据挂在这里，重启后重置
export default {
  config: {
    whitelist: ['G001','G002','G004','G006','G008'],'G002','G004','G006','G008'],
    tau: 0.85,
    t_silence: 60,
    t_max: 300,
    t_lookback: 600,
    n_freq: 3,
    dedup_window: 24 * 3600,
    at_switch: true,
    ai_mode: 'builtin',
    deepseek_key: '',
    deepseek_base: 'https://api.deepseek.com/v1/chat/completions',
    deepseek_model: 'deepseek-chat',
    dify_url: '',
    dify_key: '',
  },
  replay: {
    playing: false,
    speed: 1,
    cursor: 0,
    startedAt: null,
    elapsedBase: 0,
  },
  windows: new Map(),
  demands: [],
  responses: [],
  scheduleReplacements: [],
  dailyCount: {},
  counters: {
    intake: 0,
    filtered: 0,
    aggregated: 0,
    bert_pass: 0,
    bert_fail: 0,
    parsed: 0,
    deduped: 0,
    freq_blocked: 0,
    routed_at: 0,
    routed_non_at: 0,
    responded: 0,
  },
  logs: [],
};
